sudo: false
language: python
python:
    - "3.6"
node_js:
    - 8.12
install:
  - pip install tox-travis
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

jobs:
  include:
    - stage: vue build
      language: node_js
      script: 
        - cd frontend
        - npm run build
        - cd ../
    - stage: test backend
      language: python
      script:
        - tox
    - stage: test frontend
      language: python
      script:
        - python server.py &
        - $(npm bin)/cypress run 