matrix:
  - language: python
    sudo: false
    python:
        - "3.6"
    install: pip install tox-travis
    script: tox
  - language: node_js
    node_js:
      - 10
    cache:
      # Caches $HOME/.npm when npm ci is default script command
      # Caches node_modules in all other cases
      npm: true
      directories:
        # we also need to cache folder with Cypress binary
        - ~/.cache
    install:
      - npm ci
    script:
      - $(npm bin)/cypress run --record